import { describe, it, expect, beforeEach, vi } from 'vitest';
import { renderHook, act } from '@testing-library/react';
import { useSharedUserId, __resetSharedUserIdForTests } from './useSharedUserId';

describe('useSharedUserId', () => {
  beforeEach(() => {
    window.localStorage.clear();
    __resetSharedUserIdForTests();
  });

  it('gives two instances mounted together the same id, never a divergent one', async () => {
    const setItemSpy = vi.spyOn(window.localStorage.__proto__, 'setItem');

    const a = renderHook(() => useSharedUserId());
    const b = renderHook(() => useSharedUserId());

    await act(async () => {
      await Promise.resolve();
    });

    const idA = a.result.current[0];
    const idB = b.result.current[0];

    expect(idA).toBeTruthy();
    expect(idA).toBe(idB);
    expect(window.localStorage.getItem('tanker_tracker_user_id')).toBe(idA);

    // Every write to the key must carry the same value — no second,
    // divergent id generated by the second instance racing the first.
    const userIdWriteValues = setItemSpy.mock.calls
      .filter(([key]) => key === 'tanker_tracker_user_id')
      .map(([, value]) => value);
    expect(userIdWriteValues.length).toBeGreaterThan(0);
    expect(new Set(userIdWriteValues).size).toBe(1);

    setItemSpy.mockRestore();
    a.unmount();
    b.unmount();
  });

  it('reuses an already-persisted id instead of generating a new one', async () => {
    window.localStorage.setItem('tanker_tracker_user_id', 'existing-id');

    const { result } = renderHook(() => useSharedUserId());

    await act(async () => {
      await Promise.resolve();
    });

    expect(result.current[0]).toBe('existing-id');
  });
});
